Repository thorvg/thorvg.viewer, pull requests merged in 2023-11, with the labels that each got.

#9 Support new formats - jpg, png
  index.html
  main.js
Labels: enhancement

#11 Enable lottie file again,
  index.html
Labels: bug

#12 view: Fix broken UI
  style.css
Labels: UI

#15 Remove the scene-graph function.
  index.html
  main.js
Labels: enhancement

#16 removed highlight feature
  main.js
Labels: enhancement

#10 Removed the tvg compression option from the export
  main.js
  thorvg-wasm.js
  thorvg-wasm.wasm
Labels: enhancement

#17 Minor patches on filetype checking
  main.js
Labels: bug, enhancement
