Repository thorvg/thorvg.viewer, pull requests merged in 2024-01, with the labels that each got.

#24 wasm: update v0.12.0 released binary
  index.html
  main.js
  thorvg-wasm.js
  thorvg-wasm.wasm
Labels: enhancement

#26 ui: delete the decimal information of the frame number.
  main.js
Labels: UI

#23 Major Upgrade: Integrate `@thorvg/lottie-player`
  index.html
  lottie-player.js
  main.js
  style.css
Labels: enhancement

#29 Fix typo
  main.js
Labels: bug

#30 Fix file upload clicking
  style.css
Labels: bug

#32 wasm: Update v0.12.2 released binary
  index.html
  lottie-player.js
Labels: enhancement

#34 Hide drop file(canvas) text when using loadURL
  main.js
Labels: bug, UI

#35 wasm: Update v0.12.3 released binary
  index.html
  lottie-player.js
Labels: enhancement
